# Generated by Django 3.1.6 on 2021-02-06 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210205_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
